spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

  cloud:
    gateway:
      routes:
#        - id: post
#          uri: http://localhost:8089
#          predicates:
#            - Path=/posts/**            # Maps to RequestMapping("[THIS]") in the post-service
#        - id: timeline
#          uri: http://localhost:8088
#          predicates:
#            - Path=/timeline/**
#        - id: anyInPost
#          uri: http://localhost:8089
#          predicates:
#            - Path=**
#        - id: anyInTimeline
#          uri: http://localhost:8088
#          predicates:
#            - Path=**
        - id: post
          uri: http://post-service-service.default.svc.cluster.local
          predicates:
            - Path=/posts/**
        - id: timeline
          uri: http://timeline-service-service.default.svc.cluster.local
          predicates:
            - Path=/timeline/**
        - id: anyInPost
          uri: http://post-service-service.default.svc.cluster.local
          predicates:
            - Path=**
        - id: anyInTimeline
          uri: http://timeline-service-service.default.svc.cluster.local
          predicates:
            - Path=**